name: 🐛 Hata Bildirimi
description: LaTeX derleme hatası, içerik hatası veya format sorunu bildir
title: "[BUG] "
labels: ["type:bug", "needs-triage"]
assignees: ["yusufarbc"]

body:
  - type: markdown
    attributes:
      value: |
        🐛 **Hata bildirimi için teşekkürler!** 
        
        Lütfen aşağıdaki bilgileri mümkün olduğunca detaylı doldurun.
        
  - type: checkboxes
    id: search-existing
    attributes:
      label: 🔍 Mevcut Issues Kontrolü
      description: Bu hatanın daha önce bildirilip bildirilmediğini kontrol ettiniz mi?
      options:
        - label: Mevcut açık issue'lara baktım ve aynı sorunu bulamadım
          required: true
          
  - type: dropdown
    id: bug-category
    attributes:
      label: 🏷️ Hata Kategorisi
      description: Bu hata hangi kategoride?
      options:
        - LaTeX Derleme Hatası
        - İçerik/Yazım Hatası  
        - Tablo Format Problemi
        - Görsel/Resim Sorunu
        - Referans/Link Hatası
        - PDF Çıktı Problemi
        - README/Dokümantasyon
        - Diğer
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: affected-chapter
    attributes:
      label: 📚 Etkilenen Bölüm
      description: Hangi bölümde sorun var?
      options:
        - "Genel (main.tex, README.md)"
        - "Bölüm 1: Bilgi Güvenliği"  
        - "Bölüm 2: Ağ Güvenliği"
        - "Bölüm 3: Endpoint Güvenliği"
        - "Bölüm 4: Uygulama Güvenliği"
        - "Bölüm 5: Bulut Güvenliği"
        - "Bölüm 6: Donanım Güvenliği"
        - "Bölüm 7: Kimlik Yönetimi"
        - "Bölüm 8: Tehdit İstihbaratı"
        - "Bölüm 9: Olay Müdahale"
        - "Bölüm 10: Risk Yönetimi"
        - "Bölüm 11: Sızma Testi"
        - "Bölüm 12: Malware Analizi"
        - "Bölüm 13: Sosyal Mühendislik"
        - "Bölüm 14: SOC/NOC Yönetimi"
      default: 0
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Hata Açıklaması
      description: Karşılaştığınız sorunu detaylı olarak açıklayın
      placeholder: |
        Örnek: "data/12.tex dosyasının 84. satırında longtable ortamı yanlış kapatılmış..."
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Hatayı Tekrarlamak İçin Adımlar
      description: Bu hatayı nasıl tekrarlarız?
      placeholder: |
        1. `xelatex main.tex` komutunu çalıştır
        2. Şu hatayı ver: ...
        3. Satır X'te sorun oluşuyor
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Beklenen Davranış
      description: Ne olması gerekiyordu?
      placeholder: "LaTeX'in hatasız derlenmesi ve PDF'in oluşması bekleniyor"
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior  
    attributes:
      label: ❌ Gerçek Davranış
      description: Bunun yerine ne oluyor?
      placeholder: "Derleme hatası alıyorum ve PDF oluşmuyor"
    validations:
      required: true
      
  - type: textarea
    id: error-output
    attributes:
      label: 🖥️ Hata Çıktısı
      description: Konsol/terminal'den aldığınız hata mesajları
      render: shell
      placeholder: |
        ! LaTeX Error: \begin{longtable} on input line 38 ended by \end{customlongtable}.
        
  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Ortam Bilgileri
      description: Hangi sistem/araçları kullanıyorsunuz?
      value: |
        **İşletim Sistemi:** (Windows 11, Ubuntu 22.04, macOS, vs.)
        **LaTeX Dağıtımı:** (MiKTeX, TeX Live)
        **Editör:** (VS Code, TeXstudio, vs.)
        **XeLaTeX Versiyonu:** (`xelatex --version` çıktısı)
        
  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Ek Bilgiler
      description: Ekran görüntüleri, log dosyaları, veya diğer yararlı bilgiler
      placeholder: "Buraya dosya yükleyebilir veya ek açıklamalar yazabilirsiniz"
      
  - type: checkboxes
    id: contribution-intent
    attributes:
      label: 🤝 Katkı İsteği
      description: Bu sorunu çözmek için yardım edebilir misiniz?
      options:
        - label: Bu sorunu çözmeye yardım etmek istiyorum
        - label: Çözüm önerisi var
        - label: Sadece bildirmek istiyorum